# Generated by Django 2.0.6 on 2018-07-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180710_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('全球', '全球'), ('政治', '政治'), ('科技', '科技'), ('科学', '科学'), ('体育', '体育'), ('健康', '健康')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='news', to='news.Tag'),
        ),
    ]
