# Generated by Django 2.0.6 on 2018-07-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180710_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
