# Generated by Django 2.0.6 on 2018-07-10 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pub_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
