# Generated by Django 2.0.6 on 2018-07-10 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0007_auto_20180711_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
