# Generated by Django 2.0.6 on 2018-07-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_checkable'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkable',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
