# Generated by Django 2.0.6 on 2018-07-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20180711_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readrecord',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='news',
            name='review_pass',
            field=models.BooleanField(default=False),
        ),
    ]
